apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: monolithic-app
  template:
    metadata:
      labels:
        app: monolithic-app
    spec:
      containers:
      - name: monolithic-app
        image: monolithic-app:latest 
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: monolithic-app
spec:
  selector:
    app: monolithic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000